easyconfigs:
  - buildtools-26.03-bootstrap.eb
  - buildtools-python-26.03-systemPython.eb
  - buildtools-python-26.03-cray-python3.11.eb
  - syslibs-26.03-static.eb
  - buildtools-26.03.eb
  - systools-26.03.eb
  - Lzip-tools-26.03.eb
  - lumi-CPEtools-1.0.eb
  - nano-9.0.eb       # System nano is good enough though so update not really needed
#  - Vim-9.2.0063.eb  # System nano is good enough
  - git-2.54.0.eb
  - Subversion-1.14.5.eb
#  - Eigen-5.0.1.eb          # Removed from CrayEnv
#  - xorg-macros-1.20.2.eb   # Removed from CrayEnv
#  - lumi-container-wrapper-0.4.2-cray-python-default.eb  # Ready but makes no sense in a containerised environment.
#  - cotainr-2026.03.0.eb    # Ready but makes no sense in a containerised environment.
  - parallel-20260622.eb
  - lumi-CrayPath-0.1.eb
#  - rocm-6.4.4.eb
#  - amd-6.4.4.eb
#  - AMD-flang-experimental-23.2.1-cray-mpich-8.1.33.eb
