software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['22.08', '22.08-noPython']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '22.08':
            versionsuffix: '-static'
  systools:
    toolchains:
      SYSTEM:
        versions: ['22.08']
  lumi-CPEtools:
    toolchains:
      SYSTEM:
        versions: ['1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['6.4']
  Vim:
    toolchains:
      SYSTEM:
        versions: ['8.2.5172','9.0.0193']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.37.2']
  Subversion:
    toolchains:
      SYSTEM:
        versions: ['1.14.2']
  lumi-container-wrapper:
    toolchains:
      SYSTEM:
        versions:
          '0.2.6':
            versionsuffix: '-cray-python-default'
  cotainr:
    toolchains:
      SYSTEM:
        versions: ['2023.01.0']
#  rocm:
#    toolchains:
#      SYSTEM:
#        versions: ['5.1.4']

