software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['22.08', '22.08-noPython']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '22.08':
            versionsuffix: '-static'
  systools:
    toolchains:
      SYSTEM:
        versions: ['22.08']
  lumi-CPEtools:
    toolchains:
      cpeAOCC-22.08:
        versions: ['1.0']
      cpeCray-22.08:
        versions: ['1.0']
      cpeGNU-22.08:
        versions: ['1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['6.4']
  Vim:
    toolchains:
      SYSTEM:
        versions: ['8.2.5172','9.0.0193']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.37.2']
  Subversion:
    toolchains:
      SYSTEM:
        versions: ['1.14.2']
  Eigen:
    toolchains:
      SYSTEM:
        versions: ['3.4']
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: ['1.19.3']
  lumi-container-wrapper:
    toolchains:
      SYSTEM:
        versions:
          '0.2.6':
            versionsuffix: '-cray-python-3.9.12.1'
          '0.3.1':
            versionsuffix: '-cray-python-3.9.12.1'
  cotainr:
    toolchains:
      SYSTEM:
        versions: 
          '2023.01.0':
            versionsuffix: '-cray-python-3.9.12.1'
  Rust:
    toolchains:
      SYSTEM:
        versions: ['1.60.0']
  parallel:
    toolchains:
      SYSTEM:
        versions: ['20230222']
  lumi-CrayPath:
    toolchains:
      SYSTEM:
        versions: ['0.1']


