# Software to go in the system partition.
#
software:
  lumi-workspaces:
    toolchains:
      SYSTEM:
        versions: ['0.1']
  lumi-tools:
    toolchains:
      SYSTEM:
        versions: ['23.01']
  lumi-vnc:
    toolchains:
      SYSTEM:
        versions: ['20221010','20230110']
  Vampir:
    toolchains:
      SYSTEM:
        versions: ['10.0.0']
  ARMForge:
    toolchains:
      SYSTEM:
        versions: ['22.0.1']
  lumi-tools:
    toolchains:
      SYSTEM:
        versions: ['23.03']
  lumio-ext-tools:
    toolchains:
      SYSTEM:
        versions: ['1.0.0']
  lumio:
    toolchains:
      SYSTEM:
        versions: ['1.0.0']
  