easyconfigs:
  - buildtools-23.09-bootstrap.eb
  - syslibs-23.09-static.eb
  - buildtools-23.09.eb
  - buildtools-python-23.09-systemPython.eb
  - buildtools-python-23.09-cray-python3.10.eb
  - systools-23.09.eb
  - nano-7.2.eb
  - Vim-9.0.1392.eb
  - git-2.42.1.eb
  - Subversion-1.14.2.eb
  - Eigen-3.4.0.eb
  - xorg-macros-1.20.0.eb
#  - lumi-container-wrapper-0.3.1-cray-python-3.9.13.1.eb
#  - cotainr-2023.01.0-cray-python-3.9.12.1.eb
#  - Rust-1.55.0.eb
  - parallel-20231022.eb
  - lumi-CrayPath-0.1.eb
  