easyconfigs:
# Block 1
  - Blosc-1.21.6-cpeCray-25.03.eb
  - Brotli-1.1.0-cpeCray-25.03.eb
  - bzip2-1.0.8-cpeCray-25.03.eb
  - DB-18.1.40-cpeCray-25.03.eb
  - double-conversion-3.3.1-cpeCray-25.03.eb
  - expat-2.6.4-cpeCray-25.03.eb
  - FriBidi-1.0.16-cpeCray-25.03.eb
  - gc-8.2.8-cpeCray-25.03.eb
  - giflib-5.2.2-cpeCray-25.03.eb
  - GMP-6.3.0-cpeCray-25.03.eb
  - googletest-1.17.0-cpeCray-25.03.eb
  - GSL-2.8-cpeCray-25.03-sequential.eb
  - GSL-2.8-cpeCray-25.03-OpenMP.eb
  - gzip-1.14-cpeCray-25.03.eb
  - ICU-76.1-cpeCray-25.03.eb
  - libaec-1.1.4-cpeCray-25.03.eb
  - libb2-0.98.1-cpeCray-25.03.eb
  - libcerf-2.5-cpeCray-25.03.eb
  - libdeflate-1.24-cpeCray-25.03.eb
  - libffi-3.4.5-cpeCray-25.03.eb
  - libidn2-2.3.7-cpeCray-25.03.eb
  - libjpeg-turbo-3.1.0-cpeCray-25.03.eb
  - libogg-1.3.6-cpeCray-25.03.eb
  - libopus-1.5.2-cpeCray-25.03.eb
  - libtirpc-1.3.6-cpeCray-25.03.eb
  - LMDB-0.9.31-cpeCray-25.03.eb
  - lz4-1.10.0-cpeCray-25.03.eb
  - Lzip-1.25-cpeCray-25.03.eb
  - LZO-2.10-cpeCray-25.03.eb
  - mpdecimal-4.0.1-cpeCray-25.03.eb
  - ncurses-6.5-cpeCray-25.03.eb
  - nlohmann-json-3.12.0-cpeCray-25.03.eb
  - Szip-2.1.1-cpeCray-25.03.eb
  - termcap-1.3.1-cpeCray-25.03.eb # Haven't found how to get rid of it for for Term::ReadLine::Gnu
  - x264-20250619-cpeCray-25.03.eb
  - x265-4.1-cpeCray-25.03.eb
  - zlib-1.3.1-cpeCray-25.03.eb
# Block 2
  - FLAC-1.5.0-cpeCray-25.03.eb
  - gettext-0.24-cpeCray-25.03-minimal.eb
  - JasPer-4.2.8-cpeCray-25.03.eb
  - LAME-3.100-cpeCray-25.03.eb
  - libevent-2.1.12-cpeCray-25.03.eb
  - libpciaccess-0.18.1-cpeCray-25.03.eb
  - libpng-1.6.47-cpeCray-25.03.eb
  - libreadline-8.2.13-cpeCray-25.03.eb
  - libvorbis-1.3.7-cpeCray-25.03.eb
  - MPFR-4.2.2-cpeCray-25.03.eb
  - Perl-5.40.0-cpeCray-25.03.eb
  - snappy-1.2.2-cpeCray-25.03.eb
  - Tcl-8.6.16-cpeCray-25.03.eb
  - UDUNITS-2.2.28-cpeCray-25.03.eb
## Block 3
  - freetype-2.13.3-cpeCray-25.03.eb
  - libiconv-1.18-cpeCray-25.03.eb
  - libsndfile-1.2.2-cpeCray-25.03.eb
  - MPC-1.3.1-cpeCray-25.03.eb
  - PCRE2-10.45-cpeCray-25.03.eb
  - pixman-0.42.2-cpeCray-25.03.eb
  - SQLite-3.47.2-cpeCray-25.03.eb
  - XZ-5.6.3-cpeCray-25.03.eb
## Block 4
  - file-5.46-cpeCray-25.03.eb
  - libunistring-1.3-cpeCray-25.03.eb
  - libunwind-1.8.1-cpeCray-25.03.eb
  - libxml2-2.13.4-cpeCray-25.03.eb
  - zstd-1.5.7-cpeCray-25.03.eb
## Block 5
  - Boost-1.88.0-cpeCray-25.03.eb
  - gettext-0.24-cpeCray-25.03.eb
  - libarchive-3.7.7-cpeCray-25.03.eb
  - libpsl-0.21.5-cpeCray-25.03.eb
  - LibTIFF-4.7.0-cpeCray-25.03.eb
  - libxslt-1.1.42-cpeCray-25.03.eb
## Block 6
## TODO: New Boost.python.
  - cURL-8.11.1-cpeCray-25.03.eb
  - gdbm-1.25-cpeCray-25.03.eb
  - intltool-0.51.0-cpeCray-25.03.eb
  - libwebp-1.5.0-cpeCray-25.03.eb
  - LittleCMS-2.17-cpeCray-25.03.eb
  - util-linux-2.40.4-cpeCray-25.03.eb
  - wget-1.25.0-cpeCray-25.03.eb
## Block 7
  - fontconfig-2.16.2-cpeCray-25.03.eb
  - OpenJPEG-2.5.3-cpeCray-25.03.eb
  - PROJ-9.6.2-cpeCray-25.03.eb
## Block 8
  - libgd-2.3.3-cpeCray-25.03.eb
  - X11-25.03-cpeCray-25.03.eb
## Block 9
  - FFmpeg-7.1.1-cpeCray-25.03.eb
  - Tk-8.6.16-cpeCray-25.03.eb
## Block 10
## Block 11
## Block 12
## Some libraries from the apps section of before, and applications(s)
##  - ELPA: Wait a bit, it looks like we need multiple versions and that it may need more testing.
  - METIS-5.1.0-cpeCray-25.03.eb
  - ParMETIS-4.0.3-cpeCray-25.03.eb
  - SCOTCH-6.1.3-cpeCray-25.03.eb
  - SCOTCH-7.0.8-cpeCray-25.03.eb
#  - ESMF-8.6.0-cpeCray-25.03.eb
#  - ESMF-8.6.0-cpeCray-25.03-MPI-PIO.eb
  - SuiteSparse-5.13.0-cpeCray-25.03-OpenMP.eb
## Some apps
  - lumi-CPEtools-1.2-cpeCray-25.03-hpcat-0.9.eb
##  - VampirServer
##  - Score-P
##
## Low-priority packages
##
## Line 1: Extensions for Perl
##
## With block 4
#  #- Perl-packages-CPAN-5.40.0-cpeCray-25.03.eb # May need a step-by-step install, I've seen it fail...
##
## Line 2: Gnome graphics
##
## With block 7
  - GLib-2.85.1-cpeCray-25.03.eb
## With block 9
  - cairo-1.18.4-cpeCray-25.03.eb
## With block 10
  - GObject-Introspection-1.84.0-cpeCray-25.03-cray-python3.11.eb
## With block 11
  - HarfBuzz-11.2.1-cpeCray-25.03.eb
## With block 12
  - Pango-1.56.3-cpeCray-25.03.eb
## With apps (as they depend on other low-priority packages)
  - gnuplot-6.0.3-cpeCray-25.03.eb
