easyconfigs:
# Block 1
  - Blosc-1.21.6-cpeGNU-25.03.eb
  - Brotli-1.2.0-cpeGNU-25.03.eb
  - bzip2-1.0.8-cpeGNU-25.03.eb
  - DB-18.1.40-cpeGNU-25.03.eb
  - double-conversion-3.3.1-cpeGNU-25.03.eb
  - expat-2.7.3-cpeGNU-25.03.eb
  - FriBidi-1.0.16-cpeGNU-25.03.eb
  - gc-8.2.8-cpeGNU-25.03.eb
  - giflib-5.2.2-cpeGNU-25.03.eb
  - GMP-6.3.0-cpeGNU-25.03.eb
  - googletest-1.17.0-cpeGNU-25.03.eb
  - graphite2-1.3.14-cpeGNU-25.03.eb   # Brought in for LUMI-D
  - GSL-2.8-cpeGNU-25.03-sequential.eb
  - GSL-2.8-cpeGNU-25.03-OpenMP.eb
  - gzip-1.14-cpeGNU-25.03.eb
  - ICU-78.1-cpeGNU-25.03.eb
  - libaec-1.1.4-cpeGNU-25.03.eb
  - libb2-0.98.1-cpeGNU-25.03.eb
  - libcerf-3.3-cpeGNU-25.03.eb
  - libdeflate-1.25-cpeGNU-25.03.eb
  - libffi-3.4.5-cpeGNU-25.03.eb
  - libidn2-2.3.8-cpeGNU-25.03.eb
  - libjpeg-turbo-3.1.3-cpeGNU-25.03.eb
  - libogg-1.3.6-cpeGNU-25.03.eb
  - libopus-1.5.2-cpeGNU-25.03.eb
  - libtirpc-1.3.6-cpeGNU-25.03.eb
  - LMDB-0.9.31-cpeGNU-25.03.eb
  - lz4-1.10.0-cpeGNU-25.03.eb
  - Lzip-1.25-cpeGNU-25.03.eb
  - LZO-2.10-cpeGNU-25.03.eb
  - Mako-1.3.10-cpeGNU-25.03.eb        # Brought in for LUMI-D
  - mpdecimal-4.0.1-cpeGNU-25.03.eb
  - ncurses-6.5-cpeGNU-25.03.eb
  - nlohmann-json-3.12.0-cpeGNU-25.03.eb
  - oneTBB-2022.2.0-cpeGNU-25.03.eb    # Brought in for LUMI-D
  - Szip-2.1.1-cpeGNU-25.03.eb
  - termcap-1.3.1-cpeGNU-25.03.eb # Haven't found how to get rid of it for for Term::ReadLine::Gnu
  - x264-20250831-cpeGNU-25.03.eb
  - x265-4.1-cpeGNU-25.03.eb
  - zlib-1.3.1-cpeGNU-25.03.eb
# Block 2
  - FLAC-1.5.0-cpeGNU-25.03.eb
  - gettext-0.24-cpeGNU-25.03-minimal.eb
  - JasPer-4.2.8-cpeGNU-25.03.eb
  - LAME-3.100-cpeGNU-25.03.eb
  - libevent-2.1.12-cpeGNU-25.03.eb
  - libpciaccess-0.18.1-cpeGNU-25.03.eb
  - libpng-1.6.53-cpeGNU-25.03.eb
  - libreadline-8.3-cpeGNU-25.03.eb
  - libvorbis-1.3.7-cpeGNU-25.03.eb
  #- LLVM-18.1.8-cpeGNU-25.03.eb    # Brought in for LUMI-D
  - MPFR-4.2.2-cpeGNU-25.03.eb
  - Perl-5.40.2-cpeGNU-25.03.eb
  - snappy-1.2.2-cpeGNU-25.03.eb
  - Tcl-8.6.16-cpeGNU-25.03.eb
  - UDUNITS-2.2.28-cpeGNU-25.03.eb
## Block 3
  - freetype-2.13.3-cpeGNU-25.03.eb
  - libiconv-1.18-cpeGNU-25.03.eb
  - libsndfile-1.2.2-cpeGNU-25.03.eb
  - MPC-1.3.1-cpeGNU-25.03.eb
  - PCRE2-10.45-cpeGNU-25.03.eb
  - pixman-0.42.2-cpeGNU-25.03.eb
  - SQLite-3.47.2-cpeGNU-25.03.eb
  - XZ-5.6.3-cpeGNU-25.03.eb
## Block 4
  - file-5.46-cpeGNU-25.03.eb
  - libunistring-1.3-cpeGNU-25.03.eb
  - libunwind-1.8.1-cpeGNU-25.03.eb
  - libxml2-2.13.4-cpeGNU-25.03.eb
  - zstd-1.5.7-cpeGNU-25.03.eb
## Block 5
  - Boost-1.90.0-cpeGNU-25.03.eb
  - gettext-0.26-cpeGNU-25.03.eb
  - libarchive-3.8.4-cpeGNU-25.03.eb
  - libpsl-0.21.5-cpeGNU-25.03.eb
  - LibTIFF-4.7.0-cpeGNU-25.03.eb
  - libxslt-1.1.42-cpeGNU-25.03.eb
## Block 6
## TODO: New Boost.python.
  - cURL-8.17.0-cpeGNU-25.03.eb
  - gdbm-1.26-cpeGNU-25.03.eb
  - intltool-0.51.0-cpeGNU-25.03.eb
  - libwebp-1.6.0-cpeGNU-25.03.eb
  - LittleCMS-2.17-cpeGNU-25.03.eb
  - util-linux-2.41.3-cpeGNU-25.03.eb
  - wget-1.25.0-cpeGNU-25.03.eb
## Block 7
  - fontconfig-2.17.0-cpeGNU-25.03.eb
  - OpenJPEG-2.5.4-cpeGNU-25.03.eb
  - PROJ-9.7.0-cpeGNU-25.03.eb
## Block 8
  - libgd-2.3.3-cpeGNU-25.03.eb
  - X11-25.03-cpeGNU-25.03.eb
## Block 9
  - FFmpeg-7.1.3-cpeGNU-25.03.eb
  #- OpenGL-25.03-cpeGNU-25.03.eb    # Brought in for LUMI-D
  - Tk-8.6.16-cpeGNU-25.03.eb
## Block 10
## Block 11
## Block 12
## Some libraries from the apps section of before, and applications(s)
  - METIS-5.1.0-cpeGNU-25.03.eb
  - ParMETIS-4.0.3-cpeGNU-25.03.eb
  - SCOTCH-6.1.3-cpeGNU-25.03.eb
  - SCOTCH-7.0.8-cpeGNU-25.03.eb  # Check if the EasyBlock needs an update!
#  - ESMF-8.6.0-cpeGNU-25.03.eb
#  - ESMF-8.6.0-cpeGNU-25.03-MPI-PIO.eb
  - SuiteSparse-5.13.0-cpeGNU-25.03-OpenMP.eb
## Some apps
  - lumi-CPEtools-1.2-cpeGNU-25.03-hpcat-0.9.eb
##  - VampirServer
##  - Score-P
##
## Low-priority packages
##
## Line 1: Extensions for Perl
##
## With block 4
#  - Perl-packages-CPAN-5.40.0-cpeGNU-25.03.eb
##
## Line 2: Gnome graphics
##
## With block 7
  - GLib-2.85.1-cpeGNU-25.03.eb
## With block 9
  - cairo-1.18.4-cpeGNU-25.03.eb
## With block 10
  - GObject-Introspection-1.84.0-cpeGNU-25.03-cray-python3.11.eb
## With block 11
  - HarfBuzz-11.2.1-cpeGNU-25.03.eb
## With block 12
  - Pango-1.56.3-cpeGNU-25.03.eb
## With apps (as they depend on other low-priority packages)
  - gnuplot-6.0.3-cpeGNU-25.03.eb
