easyconfigs:
# Block 1
  - Blosc-1.21.5-cpeAMD-24.11.eb
  - Brotli-1.1.0-cpeAMD-24.11.eb
  - bzip2-1.0.8-cpeAMD-24.11.eb
  - DB-18.1.40-cpeAMD-24.11.eb
  - double-conversion-3.3.0-cpeAMD-24.11.eb
  - expat-2.6.2-cpeAMD-24.11.eb
  - FriBidi-1.0.13-cpeAMD-24.11.eb
  - gc-8.2.6-cpeAMD-24.11.eb
  - giflib-5.2.1-cpeAMD-24.11.eb
  - GMP-6.3.0-cpeAMD-24.11.eb
  - googletest-1.14.0-cpeAMD-24.11.eb
  - GSL-2.7.1-cpeAMD-24.11-sequential.eb
  - GSL-2.7.1-cpeAMD-24.11-OpenMP.eb
  - gzip-1.13-cpeAMD-24.11.eb
  - ICU-74.1-cpeAMD-24.11.eb
  - libaec-1.0.6-cpeAMD-24.11.eb
  - libb2-0.98.1-cpeAMD-24.11.eb
  - libcerf-2.3-cpeAMD-24.11.eb
  - libdeflate-1.19-cpeAMD-24.11.eb
  - libffi-3.4.4-cpeAMD-24.11.eb
  - libidn2-2.3.7-cpeAMD-24.11.eb
  - libjpeg-turbo-3.0.1-cpeAMD-24.11.eb
  - libogg-1.3.5-cpeAMD-24.11.eb
  - libopus-1.4-cpeAMD-24.11.eb
  - libpsl-0.21.5-cpeAMD-24.11.eb
  - libtirpc-1.3.4-cpeAMD-24.11.eb
  - LMDB-0.9.31-cpeAMD-24.11.eb
  - lz4-1.9.4-cpeAMD-24.11.eb
  - Lzip-1.23-cpeAMD-24.11.eb
  - LZO-2.10-cpeAMD-24.11.eb
  - mpdecimal-4.0.0-cpeAMD-24.11.eb
  - ncurses-6.4-cpeAMD-24.11.eb
  - nlohmann-json-3.11.3-cpeAMD-24.11.eb
  - Szip-2.1.1-cpeAMD-24.11.eb
  - termcap-1.3.1-cpeAMD-24.11.eb # Haven't found how to get rid of it for for Term::ReadLine::Gnu
  - x264-20231019-cpeAMD-24.11.eb
  - x265-3.5-cpeAMD-24.11.eb
  - zlib-1.3.1-cpeAMD-24.11.eb
# Block 2
#  - cURL-8.3.0-cpeAMD-24.11.eb
#  - FLAC-1.4.3-cpeAMD-24.11.eb
  - gettext-0.22-cpeAMD-24.11-minimal.eb
#  - JasPer-4.0.0-cpeAMD-24.11.eb
  - LAME-3.100-cpeAMD-24.11.eb
#  - libevent-2.1.12-cpeAMD-24.11.eb
#  - libpciaccess-0.17-cpeAMD-24.11.eb
  - libpng-1.6.40-cpeAMD-24.11.eb
  - libreadline-8.2-cpeAMD-24.11.eb
#  - libvorbis-1.3.7-cpeAMD-24.11.eb
#  - MPFR-4.2.0-cpeAMD-24.11.eb
  - Perl-5.38.0-cpeAMD-24.11.eb
#  - snappy-1.1.10-cpeAMD-24.11.eb # Does not compile right now
  - Tcl-8.6.13-cpeAMD-24.11.eb
#  - UDUNITS-2.2.28-cpeAMD-24.11.eb
## Block 3
  - freetype-2.13.2-cpeAMD-24.11.eb
#  - libiconv-1.17-cpeAMD-24.11.eb
#  - libsndfile-1.2.2-cpeAMD-24.11.eb
#  - MPC-1.3.1-cpeAMD-24.11.eb
  - PCRE2-10.42-cpeAMD-24.11.eb
#  - pixman-0.42.2-cpeAMD-24.11.eb
  - SQLite-3.43.1-cpeAMD-24.11.eb
  - XZ-5.4.4-cpeAMD-24.11.eb
## Block 4
  - file-5.43-cpeAMD-24.11.eb
#  - libunistring-1.1-cpeAMD-24.11.eb
#  - libunwind-1.6.2-cpeAMD-24.11.eb
  - libxml2-2.11.5-cpeAMD-24.11.eb
#  - wget-1.21.4-cpeAMD-24.11.eb
#  - zstd-1.5.5-cpeAMD-24.11.eb
## Block 5
#  - Boost-1.83.0-cpeAMD-24.11.eb
  - gettext-0.22-cpeAMD-24.11.eb
#  - libarchive-3.7.2-cpeAMD-24.11.eb
#  - LibTIFF-4.6.0-cpeAMD-24.11.eb
  - libxslt-1.1.38-cpeAMD-24.11.eb
## Block 6
## TODO: New Boost.python.
#  - gdbm-1.23-cpeAMD-24.11.eb
#  - intltool-0.51.0-cpeAMD-24.11.eb
#  - libwebp-1.3.2-cpeAMD-24.11.eb
#  - PROJ-9.3.1-cpeAMD-24.11.eb
  - util-linux-2.39.3-cpeAMD-24.11.eb
## Block 7
#  - fontconfig-2.14.2-cpeAMD-24.11.eb
## Block 8
#  - libgd-2.3.3-cpeAMD-24.11.eb
#  - X11-24.03-cpeAMD-24.11.eb
## Block 9
#  - FFmpeg-6.1.1-cpeAMD-24.11.eb
#  - Tk-8.6.13-cpeAMD-24.11.eb
## Block 10
## Block 11
## Block 12
## Some libraries from the apps section of before, and applications(s)
##  - ELPA: Wait a bit, it looks like we need multiple versions and that it may need more testing.
#  - METIS-5.1.0-cpeAMD-24.11.eb
#  - ParMETIS-4.0.3-cpeAMD-24.11.eb
#  - SCOTCH-6.1.3-cpeAMD-24.11.eb
#  - SuiteSparse-5.13.0-cpeAMD-24.11-OpenMP.eb
## - SCOTCH-7.0.4-cpeAMD-24.11.eb  # Check if the EasyBlock needs an update!
##  - ESMF-8.6.0-cpeAMD-24.11.eb
## Some apps
#  - lumi-CPEtools-1.1-cpeAMD-24.11.eb
#  - lumi-CPEtools-1.2-cpeAMD-24.11.eb
##  - VampirServer
##  - Score-P
##
## Low-priority packages
##
## Line 1: Extensions for Perl
##
## With block 4
####  - Perl-packages-CPAN-5.38.0-cpeAMD-24.11.eb
##
## Line 2: Gnome graphics
##
## With block 7
#  - GLib-2.78.1-cpeAMD-24.11.eb
## With block 9
#  - cairo-1.18.0-cpeAMD-24.11.eb
## With block 10
#  - GObject-Introspection-1.78.1-cpeAMD-24.11-cray-python3.11.eb
## With block 11
#  - HarfBuzz-8.2.2-cpeAMD-24.11.eb
## With block 12
#  - Pango-1.51.0-cpeAMD-24.11.eb
## With apps (as they depend on other low-priority packages)
#  - gnuplot-5.4.10-cpeAMD-24.11.eb
#
