easyconfigs:
  - buildtools-24.11-bootstrap.eb
  - syslibs-24.11-static.eb
  - buildtools-24.11.eb
  - buildtools-python-24.11-systemPython.eb
  - buildtools-python-24.11-cray-python3.11.eb
  - systools-24.11.eb
  - Lzip-tools-24.11.eb
#  - nano-8.0.eb       # System nano is good enough
#  - Vim-9.1.0447.eb   # System vim is good enough
  - git-2.49.0.eb
  - Subversion-1.14.5.eb
  - Eigen-3.4.0.eb
  - xorg-macros-1.20.0.eb  # Skip update, server was down and align with toolchain.
#  - lumi-container-wrapper-0.3.3-cray-python-3.11.7.eb  # Ready but makes no sense in a containerised environment.
#  - cotainr-2025.03.0-cray-python-3.11.7.eb  # Ready but makes no sense in a containerised environment
  - parallel-20250322.eb
  - lumi-CrayPath-0.1.eb
  
