easyconfigs:
  - buildtools-24.11-bootstrap.eb
  - syslibs-24.11-static.eb
  - buildtools-24.11.eb
  - buildtools-python-24.11-systemPython.eb
  - buildtools-python-24.11-cray-python3.11.eb
  - systools-24.11.eb
  - Lzip-tools-24.11.eb
  - lumi-CPEtools-1.0.eb
#  - nano-8.0.eb
#  - Vim-9.1.0447.eb
  - git-2.49.0.eb
  - Subversion-1.14.5.eb
#  - Eigen-3.4.0.eb          # Removed from CrayEnv
#  - xorg-macros-1.20.0.eb   # Removed from CrayEnv
#  - lumi-container-wrapper-0.3.3-cray-python-default.eb
#  - cotainr-2023.11.0-20240909.eb
##  - cotainr-2024.10.0.eb
  - parallel-20250322.eb
  - lumi-CrayPath-0.1.eb
  
