software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['22.06']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '22.06':
            versionsuffix: '-static'
  systools:
    toolchains:
      SYSTEM:
        versions: ['22.06']
  lumi-CPEtools:
    toolchains:
#      cpeAOCC-22.06:
#        versions: ['1.0']
      cpeCray-22.06:
        versions: ['1.0']
      cpeGNU-22.06:
        versions: ['1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['6.3']
  Vim:
    toolchains:
      SYSTEM:
        versions: ['8.2.5172','9.0.0016']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.37.0']
  Subversion:
    toolchains:
      SYSTEM:
        versions: ['1.14.2']
  Eigen:
    toolchains:
      SYSTEM:
        versions: ['3.4']
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: ['1.19.3']
#  lumi-container-wrapper:
#    toolchains:
#      SYSTEM:
#        versions:
#          '0.2.2':
#            versionsuffix: '-cray-python-3.9.12.1'
  rocm:
    toolchains:
      SYSTEM:
        versions: ['5.1.4']
  Rust:
    toolchains:
      SYSTEM:
        versions: ['1.60.0']

