easyconfigs:
# Block 1
  - Blosc-1.21.2-cpeCray-22.12.eb
  - Brotli-1.0.9-cpeCray-22.12.eb
  - bzip2-1.0.8-cpeCray-22.12.eb
  - DB-18.1.40-cpeCray-22.12.eb
  - double-conversion-3.2.1-cpeCray-22.12.eb
  - expat-2.4.9-cpeCray-22.12.eb
  - FriBidi-1.0.12-cpeCray-22.12.eb
  - gc-8.2.2-cpeCray-22.12.eb
  - giflib-5.2.1-cpeCray-22.12.eb
  - GMP-6.2.1-cpeCray-22.12.eb
  - GSL-2.7.1-cpeCray-22.12-sequential.eb
  - GSL-2.7.1-cpeCray-22.12-OpenMP.eb
  - gzip-1.12-cpeCray-22.12.eb
  - ICU-72.1-cpeCray-22.12.eb
  - libaec-1.0.6-cpeCray-22.12.eb
  - libb2-0.98.1-cpeCray-22.12.eb
  - libcerf-2.3-cpeCray-22.12.eb
  - libdeflate-1.15-cpeCray-22.12.eb
  - libffi-3.4.4-cpeCray-22.12.eb
#  - libidn-1.38-cpeCray-22.12.eb
  - libidn2-2.3.4-cpeCray-22.12.eb
  - libjpeg-turbo-2.1.4-cpeCray-22.12.eb
  - libogg-1.3.5-cpeCray-22.12.eb
  - libopus-1.3.1-cpeCray-22.12.eb
  - libpsl-0.21.1-cpeCray-22.12.eb
  - ncurses-6.4-cpeCray-22.12.eb
  - libtirpc-1.3.3-cpeCray-22.12.eb
  - LMDB-0.9.29-cpeCray-22.12.eb
  - lz4-1.9.4-cpeCray-22.12.eb
  - Lzip-1.23-cpeCray-22.12.eb
  - LZO-2.10-cpeCray-22.12.eb
  - mpdecimal-2.5.1-cpeCray-22.12.eb
  - ncurses-6.4-cpeCray-22.12.eb
  - Szip-2.1.1-cpeCray-22.12.eb
  - termcap-1.3.1-cpeCray-22.12.eb # Haven't found how to get rid of it for for Term::ReadLine::Gnu
  - x264-20230226-cpeCray-22.12.eb
  - x265-3.5-cpeCray-22.12.eb
  - zlib-1.2.12-cpeCray-22.12.eb
# Block 2
  - cURL-7.86.0-cpeCray-22.12.eb
  - FLAC-1.4.2-cpeCray-22.12.eb
  - gettext-0.21.1-cpeCray-22.12-minimal.eb
  - JasPer-4.0.0-cpeCray-22.12.eb
  - LAME-3.100-cpeCray-22.12.eb
  - libevent-2.1.12-cpeCray-22.12.eb
  - libpciaccess-0.17-cpeCray-22.12.eb
  - libpng-1.6.38-cpeCray-22.12.eb
  - libreadline-8.2-cpeCray-22.12.eb
  - libvorbis-1.3.7-cpeCray-22.12.eb
  - MPFR-4.2.0-cpeCray-22.12.eb
  - snappy-1.1.9-cpeCray-22.12.eb
  - Tcl-8.6.12-cpeCray-22.12.eb
  - UDUNITS-2.2.28-cpeCray-22.12.eb
# Block 3
  - freetype-2.12.1-cpeCray-22.12.eb
  - libiconv-1.17-cpeCray-22.12.eb
  - libsndfile-1.2.0-cpeCray-22.12.eb
  - MPC-1.3.1-cpeCray-22.12.eb
  #- PCRE
  - PCRE2-10.40-cpeCray-22.12.eb
  - pixman-0.42.2-cpeCray-22.12.eb
  - SQLite-3.39.4-cpeCray-22.12.eb
  - XZ-5.4.2-cpeCray-22.12.eb
# Block 4
  - file-5.43-cpeCray-22.12.eb
  - libunistring-1.1-cpeCray-22.12.eb
  - libunwind-1.6.2-cpeCray-22.12.eb
  - libxml2-2.9.14-cpeCray-22.12.eb
  - wget-1.21.3-cpeCray-22.12.eb
  - zstd-1.5.2-cpeCray-22.12.eb
# Block 5
  - Boost-1.81.0-cpeCray-22.12.eb
  - gettext-0.21.1-cpeCray-22.12.eb
  - libarchive-3.6.1-cpeCray-22.12.eb
  - LibTIFF-4.4.0-cpeCray-22.12.eb
  - libxslt-1.1.37-cpeCray-22.12.eb
  - Perl-5.36.0-cpeCray-22.12.eb
# Block 6
# TODO: New Boost.python.
  - intltool-0.51.0-cpeCray-22.12.eb
  - gdbm-1.23-cpeCray-22.12.eb
  - libwebp-1.2.4-cpeCray-22.12.eb
  - PROJ-9.1.1-cpeCray-22.12.eb
  - util-linux-2.38.1-cpeCray-22.12.eb
# Block 7
  - fontconfig-2.14.1-cpeCray-22.12.eb
  - GLib-2.75.0-cpeCray-22.12.eb
  - libgd-2.3.3-cpeCray-22.12.eb
  - X11-22.12-cpeCray-22.12.eb
# Block 8
  - cairo-1.17.4-cpeCray-22.12.eb
#  - FFmpeg-5.1.2-cpeCray-22.12.eb # Fails with CCE 15.0.0 with a compiler crash.
  - Tk-8.6.12-cpeCray-22.12.eb
# Block 9
  - GObject-Introspection-1.74.0-cpeCray-22.12-cray-python3.9.eb
# Block 10
  - HarfBuzz-5.3.1-cpeCray-22.12.eb
# Block 11
  - Pango-1.50.12-cpeCray-22.12.eb
# Some libraries from the apps section of before, and applications(s)
#  - ELPA: Wait a bit, it looks like we need multiple versions and that it may need more testing.
  - METIS-5.1.0-cpeCray-22.12.eb
  - ParMETIS-4.0.3-cpeCray-22.12.eb
  - SCOTCH-6.1.3-cpeCray-22.12.eb
#  - SCOTCH-7.0.3-cpeCray-22.12.eb  # Check if the EasyBlock needs an update!
  - ESMF-8.4.1-cpeCray-22.12.eb
# Some apps
  - lumi-CPEtools-1.0-cpeCray-22.12.eb
  - lumi-CPEtools-1.1-cpeCray-22.12.eb
  - gnuplot-5.4.6-cpeCray-22.12.eb
 #  - VampirServer
#  - Score-P

