easyconfigs:
  - Blosc-1.21.2-cpeAOCC-23.03.eb
  - Brotli-1.0.9-cpeAOCC-23.03.eb
  - bzip2-1.0.8-cpeAOCC-23.03.eb
  - DB-18.1.40-cpeAOCC-23.03.eb
  - double-conversion-3.2.1-cpeAOCC-23.03.eb
  - expat-2.4.9-cpeAOCC-23.03.eb
  - FriBidi-1.0.12-cpeAOCC-23.03.eb
  - gc-8.2.2-cpeAOCC-23.03.eb
  - giflib-5.2.1-cpeAOCC-23.03.eb
  - GMP-6.2.1-cpeAOCC-23.03.eb
  - GSL-2.7.1-cpeAOCC-23.03-sequential.eb
  - GSL-2.7.1-cpeAOCC-23.03-OpenMP.eb
  - gzip-1.12-cpeAOCC-23.03.eb
  - ICU-72.1-cpeAOCC-23.03.eb
  - libaec-1.0.6-cpeAOCC-23.03.eb
  - libb2-0.98.1-cpeAOCC-23.03.eb
  - libcerf-2.3-cpeAOCC-23.03.eb
  - libdeflate-1.15-cpeAOCC-23.03.eb
  - libffi-3.4.4-cpeAOCC-23.03.eb
#  - libidn-1.38-cpeAOCC-23.03.eb
  - libidn2-2.3.4-cpeAOCC-23.03.eb
  - libjpeg-turbo-2.1.4-cpeAOCC-23.03.eb
  - libogg-1.3.5-cpeAOCC-23.03.eb
  - libopus-1.3.1-cpeAOCC-23.03.eb
  - libpsl-0.21.1-cpeAOCC-23.03.eb
  - libtirpc-1.3.3-cpeAOCC-23.03.eb
  - LMDB-0.9.29-cpeAOCC-23.03.eb
  - lz4-1.9.4-cpeAOCC-23.03.eb
  - Lzip-1.23-cpeAOCC-23.03.eb
  - LZO-2.10-cpeAOCC-23.03.eb
  - mpdecimal-2.5.1-cpeAOCC-23.03.eb
  - ncurses-6.4-cpeAOCC-23.03.eb
  - Szip-2.1.1-cpeAOCC-23.03.eb
#  - termcap-1.3.1-cpeAOCC-23.03.eb
  - x264-20230226-cpeAOCC-23.03.eb
  - x265-3.5-cpeAOCC-23.03.eb
  - zlib-1.2.12-cpeAOCC-23.03.eb
  