easyconfigs:
# Block 1
  - Blosc-1.21.2-cpeGNU-23.03.eb
  - Brotli-1.0.9-cpeGNU-23.03.eb
  - bzip2-1.0.8-cpeGNU-23.03.eb
  - DB-18.1.40-cpeGNU-23.03.eb
  - double-conversion-3.2.1-cpeGNU-23.03.eb
  - expat-2.4.9-cpeGNU-23.03.eb
  - FriBidi-1.0.12-cpeGNU-23.03.eb
  - gc-8.2.2-cpeGNU-23.03.eb
  - giflib-5.2.1-cpeGNU-23.03.eb
  - GMP-6.2.1-cpeGNU-23.03.eb
#  - GSL-2.7.1-cpeGNU-23.03-sequential.eb
#  - GSL-2.7.1-cpeGNU-23.03-OpenMP.eb
  - gzip-1.12-cpeGNU-23.03.eb
  - ICU-72.1-cpeGNU-23.03.eb
  - libaec-1.0.6-cpeGNU-23.03.eb
  - libb2-0.98.1-cpeGNU-23.03.eb
  - libcerf-2.3-cpeGNU-23.03.eb
  - libdeflate-1.15-cpeGNU-23.03.eb
  - libffi-3.4.4-cpeGNU-23.03.eb
#  - libidn-1.38-cpeGNU-23.03.eb
  - libidn2-2.3.4-cpeGNU-23.03.eb
  - libjpeg-turbo-2.1.4-cpeGNU-23.03.eb
  - libogg-1.3.5-cpeGNU-23.03.eb
  - libopus-1.3.1-cpeGNU-23.03.eb
  - libpsl-0.21.1-cpeGNU-23.03.eb
  - libreadline-8.2-cpeGNU-23.03.eb
  - libtirpc-1.3.3-cpeGNU-23.03.eb
  - LMDB-0.9.29-cpeGNU-23.03.eb
  - lz4-1.9.4-cpeGNU-23.03.eb
  - Lzip-1.23-cpeGNU-23.03.eb
  - LZO-2.10-cpeGNU-23.03.eb
  - mpdecimal-2.5.1-cpeGNU-23.03.eb
  - ncurses-6.4-cpeGNU-23.03.eb
  - Szip-2.1.1-cpeGNU-23.03.eb
  - termcap-1.3.1-cpeGNU-23.03.eb # Haven't found how to get rid of it for for Term::ReadLine::Gnu
  - x264-20230226-cpeGNU-23.03.eb
  - x265-3.5-cpeGNU-23.03.eb
  - zlib-1.2.12-cpeGNU-23.03.eb
# Block 2
  - cURL-7.86.0-cpeGNU-23.03.eb
  - FLAC-1.4.2-cpeGNU-23.03.eb
  - gettext-0.21.1-cpeGNU-23.03-minimal.eb
  - JasPer-4.0.0-cpeGNU-23.03.eb
  - LAME-3.100-cpeGNU-23.03.eb
  - libevent-2.1.12-cpeGNU-23.03.eb
  - libpciaccess-0.17-cpeGNU-23.03.eb
  - libpng-1.6.38-cpeGNU-23.03.eb
  - libvorbis-1.3.7-cpeGNU-23.03.eb
  - MPFR-4.2.0-cpeGNU-23.03.eb
  - snappy-1.1.9-cpeGNU-23.03.eb
  - Tcl-8.6.12-cpeGNU-23.03.eb
  - UDUNITS-2.2.28-cpeGNU-23.03.eb
# Block 3
  - freetype-2.12.1-cpeGNU-23.03.eb
  - libiconv-1.17-cpeGNU-23.03.eb
  - libsndfile-1.2.0-cpeGNU-23.03.eb
  - MPC-1.3.1-cpeGNU-23.03.eb
  #- PCRE
  - PCRE2-10.40-cpeGNU-23.03.eb
  - pixman-0.42.2-cpeGNU-23.03.eb
  - SQLite-3.39.4-cpeGNU-23.03.eb
  - XZ-5.4.2-cpeGNU-23.03.eb
# Block 4
  - file-5.43-cpeGNU-23.03.eb
  - libunistring-1.1-cpeGNU-23.03.eb
  - libunwind-1.6.2-cpeGNU-23.03.eb
  - libxml2-2.9.14-cpeGNU-23.03.eb
  - wget-1.21.3-cpeGNU-23.03.eb
  - zstd-1.5.2-cpeGNU-23.03.eb
# Block 5
  - Boost-1.81.0-cpeGNU-23.03.eb
  - gettext-0.21.1-cpeGNU-23.03.eb
  - libarchive-3.6.1-cpeGNU-23.03.eb
  - LibTIFF-4.4.0-cpeGNU-23.03.eb
  - libxslt-1.1.37-cpeGNU-23.03.eb
  - Perl-5.36.0-cpeGNU-23.03.eb
# Block 6
# TODO: New Boost.python.
  - intltool-0.51.0-cpeGNU-23.03.eb
  - gdbm-1.23-cpeGNU-23.03.eb
  - libwebp-1.2.4-cpeGNU-23.03.eb
  - PROJ-9.1.1-cpeGNU-23.03.eb
  - util-linux-2.38.1-cpeGNU-23.03.eb
# Block 7
  - fontconfig-2.14.1-cpeGNU-23.03.eb
  - GLib-2.75.0-cpeGNU-23.03.eb
  - libgd-2.3.3-cpeGNU-23.03.eb
  - X11-23.03-cpeGNU-23.03.eb
# Block 8
  - cairo-1.17.4-cpeGNU-23.03.eb
  - FFmpeg-5.1.2-cpeGNU-23.03.eb
  - Tk-8.6.12-cpeGNU-23.03.eb
# Block 9
  - GObject-Introspection-1.74.0-cpeGNU-23.03-cray-python3.9.eb
# Block 10
  - HarfBuzz-5.3.1-cpeGNU-23.03.eb
# Block 11
  - Pango
# Some libraries from the apps section of before, and applications(s)
#  - ELPA: Wait a bit, it looks like we need multiple versions and that it may need more testing.
  - METIS-5.1.0-cpeGNU-23.03.eb
  - ParMETIS-4.0.3-cpeGNU-23.03.eb
  - SCOTCH-7.0.3-cpeGNU-23.03.eb  # Check if the EasyBlock needs an update!
  - ESMF
  - gnuplot
#  - VampirServer
#  - Score-P

