easyconfigs:
  - Blosc-1.21.2-cpeGNU-23.03.eb
  - Brotli-1.0.9-cpeGNU-23.03.eb
  - bzip2-1.0.8-cpeGNU-23.03.eb
  - DB-18.1.40-cpeGNU-23.03.eb
  - double-conversion-3.2.1-cpeGNU-23.03.eb
  - expat-2.4.9-cpeGNU-23.03.eb
  - FriBidi-1.0.12-cpeGNU-23.03.eb
  - gc-8.2.2-cpeGNU-23.03.eb
  - giflib-5.2.1-cpeGNU-23.03.eb
  - GMP-6.2.1-cpeGNU-23.03.eb
  - GSL-2.7.1-cpeGNU-23.03-sequential.eb
  - GSL-2.7.1-cpeGNU-23.03-OpenMP.eb
  - ncurses-6.4-cpeGNU-23.03.eb
