software:
  buildtools:
    toolchains:
      SYSTEM:
        versions: ['21.12']
  syslibs:
    toolchains:
      SYSTEM:
        versions:
          '21.12':
            versionsuffix: '-static'
  systools:
    toolchains:
      SYSTEM:
        versions: ['21.12']
  lumi-CPEtools:
    toolchains:
      cpeAOCC-21.12:
        versions: ['1.0']
      cpeCray-21.12:
        versions: ['1.0']
      cpeGNU-21.12:
        versions: ['1.0']
  nano:
    toolchains:
      SYSTEM:
        versions: ['6.2']
  Vim:
    toolchains:
      SYSTEM:
        versions: ['8.2.4487']
  git:
    toolchains:
      SYSTEM:
        versions: ['2.35.1']
  Subversion:
    toolchains:
      SYSTEM:
        versions: ['1.14.1']
  Eigen:
    toolchains:
      SYSTEM:
        versions: ['3.3.9']
  xorg-macros:
    toolchains:
      SYSTEM:
        versions: ['1.19.3']
  lumi-container-wrapper:
    toolchains:
      SYSTEM:
        versions:
          '0.2.2':
            versionsuffix: '-cray-python-3.9.4.2'
  rocm:
    toolchains:
      SYSTEM:
        versions: ['4.5.2']
  rocmlibs:
    toolchains:
      SYSTEM:
        versions: ['4.5.2']
  RCCL:
    toolchains:
      SYSTEM:
        versions: ['4.5.2']
  rocThrust:
    toolchains:
      SYSTEM:
        versions: ['4.5.2']
