easyconfigs:
  - buildtools-23.12-bootstrap.eb
  - syslibs-23.12-static.eb
  - buildtools-23.12.eb
  - buildtools-python-23.12-systemPython.eb
  - buildtools-python-23.12-cray-python3.11.eb
  - systools-23.12.eb
  - lumi-CPEtools-1.0.eb
  - nano-8.0.eb
  - Vim-9.1.0050.eb
  - git-2.43.4.eb
  - Subversion-1.14.3.eb
  - parallel-20240422.eb
  - lumi-CrayPath-0.1.eb
  