module_version( 'partition/C', 'CPUcompute' )
module_version( 'partition/G', 'GPUcompute' )
module_version( 'partition/D', 'DataVisualisation' )
module_version( 'partition/L', 'login' )
hide_version 'partition/common' )