easyconfigs:
  - buildtools-25.03-bootstrap.eb
  - syslibs-25.03-static.eb
  - buildtools-25.03.eb
  - buildtools-python-25.03-systemPython.eb
  - buildtools-python-25.03-cray-python3.11.eb
  - systools-25.03.eb
  - Lzip-tools-25.03.eb
#  - nano-8.0.eb       # System nano is good enough
#  - Vim-9.1.0447.eb   # System vim is good enough
  - git-2.49.0.eb
  - Subversion-1.14.5.eb
  - Eigen-3.4.0.eb
  - xorg-macros-1.20.2.eb 
#  - lumi-container-wrapper-0.4.2-cray-python-3.11.7.eb  # Ready but makes no sense in a containerised environment.
#  - cotainr-2025.03.0-cray-python-3.11.7.eb  # Ready but makes no sense in a containerised environment
  - parallel-20250422.eb
  - lumi-CrayPath-0.1.eb
  
