easyconfigs:
  - buildtools-25.03-bootstrap.eb
  - buildtools-python-25.03-systemPython.eb
  - buildtools-python-25.03-cray-python3.11.eb
  - syslibs-25.03-static.eb
  - buildtools-25.03.eb
  - systools-25.03.eb
  - Lzip-tools-25.03.eb
  - lumi-CPEtools-1.0.eb
  - nano-8.5.eb       # System nano is good enough though so update not really needed
#  - Vim-9.1.0447.eb  # System nano is good enough
  - git-2.49.0.eb
  - Subversion-1.14.5.eb
#  - Eigen-3.4.0.eb          # Removed from CrayEnv
#  - xorg-macros-1.20.2.eb   # Removed from CrayEnv
  - lumi-container-wrapper-0.4.2-cray-python-default.eb  # Ready but makes no sense in a containerised environment.
#  - cotainr-2025.03.0.eb    # Ready but makes no sense in a containerised environment.
  - parallel-20250422.eb
  - lumi-CrayPath-0.1.eb
  
